USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE DATABASE VHOL_BUILD_TLV;

CREATE OR REPLACE EXTERNAL VOLUME EXT_VOL_BUILD_TLV
    STORAGE_LOCATIONS = 
    (
    	(
    		NAME = 'VOL_DATALAKE'
            STORAGE_PROVIDER = 'S3'
            STORAGE_BASE_URL = 's3://se-sbx-yostrinsky-us-west-2/datalake/'
            STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::484577546576:role/role-se-sbx-s3-yostrinsky'
    	)
        
    
    ),
    ALLOW_WRITES=FALSE; 

CREATE OR REPLACE CATALOG INTEGRATION CAT_INTEGRATION_OBJ_STORE
  CATALOG_SOURCE=OBJECT_STORE
  TABLE_FORMAT=ICEBERG
  ENABLED=TRUE;

CREATE OR REPLACE WAREHOUSE VW_VHOL_BUILD_TLV WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 5, AUTO_RESUME= TRUE;

CREATE ROLE IF NOT EXISTS VHOL_BUILD_TLV_DE;
GRANT OWNERSHIP ON DATABASE VHOL_BUILD_TLV TO ROLE VHOL_BUILD_TLV_DE;
GRANT OWNERSHIP ON WAREHOUSE VW_VHOL_BUILD_TLV TO ROLE VHOL_BUILD_TLV_DE;
GRANT USAGE ON EXTERNAL VOLUME EXT_VOL_BUILD_TLV TO ROLE VHOL_BUILD_TLV_DE;
GRANT USAGE ON INTEGRATION CAT_INTEGRATION_OBJ_STORE TO ROLE VHOL_BUILD_TLV_DE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE VHOL_BUILD_TLV_DE;



SET MYNAME = CURRENT_USER();
GRANT ROLE VHOL_BUILD_TLV_DE TO USER IDENTIFIER($MYNAME);

USE ROLE VHOL_BUILD_TLV_DE;
USE DATABASE VHOL_BUILD_TLV;
CREATE SCHEMA RAW_LAKE;
CREATE SCHEMA RAW_STREAM;
CREATE SCHEMA TRANSFORMED;
CREATE SCHEMA ANALYTICS;
