USE ROLE VHOL_BUILD_TLV_DE;
USE WAREHOUSE VW_VHOL_BUILD_TLV;
USE DATABASE VHOL_BUILD_TLV;
USE SCHEMA RAW_LAKE;

CREATE ICEBERG TABLE stock_prices_hist
  EXTERNAL_VOLUME='EXT_VOL_BUILD_TLV'
  CATALOG='CAT_INTEGRATION_OBJ_STORE'
  METADATA_FILE_PATH='stock_prices/metadata/v1711433511541000000.metadata.json';  

SELECT COUNT (*) from stock_prices_hist;
