USE ROLE VHOL_BUILD_TLV_DE;
USE WAREHOUSE VW_VHOL_BUILD_TLV;
USE DATABASE VHOL_BUILD_TLV;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE DYNAMIC TABLE TICKER_LIVE_AND_HIST
LAG = '1 minute'
WAREHOUSE = 'VW_VHOL_BUILD_TLV'
AS 
SELECT * FROM VHOL_BUILD_TLV.TRANSFORMED.LIMIT_ORDERS_SUMMARY_DT
JOIN VHOL_BUILD_TLV.TRANSFORMED.STOCKS_TO_DATE USING (TICKER);

SELECT * FROM TICKER_LIVE_AND_HIST ORDER BY TICKER, POSITION;
